#include <iostream>
#include <fstream>
using namespace std;

int writeFile () {
    ofstream myfile;
    myfile.open ("LemonBot.txt");
    myfile << "                                                                .....',,;;;;;;;;,,,;;;::::;;;;,'....\n";
    myfile << "                                                             ...,ldxxO0KKKKKKKKKKKKKKKXXXK0OOOxoc;,.\n";
    myfile << "                                                            ...':okOO0KXXXKKKKKK000000000Okkxxdoc::,'''..\n";
    myfile << "                                                           .;odxdolllcc:::;;;;;;;,,,,'''.''''',:clodxO0kc.\n";
    myfile << "                                                           .l0NN0o:;,'...............      ....;codk0XNKd,.\n";
    myfile << "                                                         ..'lOXX0xollc:;;;;;;;;;;;::::;;;;::ccccccldxOOkdc;;,.\n";
    myfile << "                                                       .',;:okOOOkkkkkkkkxkkkkkkkkkkkkkkkkkxkkxoc::lodxddoool,.\n";
    myfile << "                                                      ..,::coxOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkxolldxkkkkxxdo;.\n";
    myfile << "                                              ..'';:cllodxxxkOO00OOOOOOOOOOOOOOOOOOOO000000000000000KXXK0OOkxc.\n";
    myfile << "                                             ..,:coxOOO0000000000000000OOOOOOOOOO000000KKKKKKKKKXXXXXNNXK000ko,....\n";
    myfile << "                                         ..',;coddk0KXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNNNNNNNNNNNWWWWWWWWWWWWNNNNKOkkdc'.\n";
    myfile << "                                        .;dO00KXNNNWWWWWWWWWWWWWWWWMMMMWMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMWWWNNN0d;....\n";
    myfile << "                                     ....ckXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNX0xdoo:'.\n";
    myfile << "                                   .;oxxxOXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNXOc.\n";
    myfile << "                                 ..'lKWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWKd:,,.\n";
    myfile << "                               .';:lxXWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMWWXK0Ol.\n";
    myfile << "                              .;xKXXNWMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWXx,.\n";
    myfile << "                           ...'cONWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWN0dllc,.\n";
    myfile << "                          .,ldxOXWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK0Okc.\n";
    myfile << "                          .:OXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMWNXKK0o;...\n";
    myfile << "                      ....,o0NNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMWWWWWXkl;,'.\n";
    myfile << "                     .,loodOXWWWWWMMMMWWWWMMWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNWWWWWWMMMMMMMMMMMMWN0dlc;.\n";
    myfile << "                     .:dkxk0NWMWWNNNXKK0000000OOOkO0KXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdollcccccoooodxkkOKNWWWWWMMMMMMMMMMMWNK0Oxc.\n";
    myfile << "                   ..'l0XXXNWWWNKOOkdc,,,,''.......;oxxx0NWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo'...    ..''';clox0XWWWWWMMMMMMMMMMMWWNNN0o'\n";
    myfile << "                  ...,dKWWWWWWNXOdddl'.....        'lddxONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd;''........''',;;:ldxxkKNWWWWWMMMMMMWWWWNKd,...\n";
    myfile << "                 .,:coOXWWWXOkxo:,,,'...........  .;dkxk0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkocc:,''.......     ...,oKWWWWWWMMMMMMMMWWXk:'...\n";
    myfile << "                 ,oO0KXWWWNOl;'..           .......:dkkOKNWWMMMWWWWWWWMMMWWWWMMWWWMMMMMMMWNOdoll:;;;,''''....... .'l0NNNWWMMMMMMMWMMWNOl:;;'.\n";
    myfile << "                .,dKXXNWMWNOo:;,'....'',,,;;;::cc:cdO00KXWWMWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMWXK0000OOOOOOOOOkkkxl;'';oOKKKXWWMWMMMMMMMWWKkxdd:.\n";
    myfile << "             ....:kXWWWWMWWKkxdddxxxkO0KKKKKKXXXXXXNNWWWWWWMMWWWWWWNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKxc,,:ok000XWWMMMMMMMMMMWX0OOxc.\n";
    myfile << "             .'',cONWMMMMWWX0kkkOOOO0XNNNNNXXXXKKKKKKKK000000OOOOOOkkxxxxxxxxxxxxxxxxxxxxddxdxxxxkkkkO0OO0XNNX0kxxk0XNXXNWMMMMMMMMMMMWNXXXKd.\n";
    myfile << "             ';::o0NWMMMMWWN0Okkddooooooollc::;;,,,,,,''''''.....................................''',:lccoOXNWNNNNWWWWWWWMMMMMMMMMMMMMWWWWNx,\n";
    myfile << "            .,cookKNWMMMMWWN0Okxl:::;,'''.....                                                  .....,;,,:dkOOO0000KNWWWWMMMMMMMMMMMMMWWWWNk,\n";
    myfile << "            .,oxxOXWWWNK00Oxoc::,'''.......                                                              ......,,,;lkKKKNWMMMMMMMMMMMMMMMWNO:....\n";
    myfile << "            .:x00KNWWN0o:;,'.                                                                                  ....,okkk0XNNWWWWMMMMMMMMMMWOc'...\n";
    myfile << "            .:kKXNWWWNkc'...                                                                                       ..'',:oxxkKNWMMMMMMMMMMW0o;;;'.\n";
    myfile << "          ...ckKXNWWWXx;..                                                                                              .';:lkNWMMMMMMMMMMWKxc::,.\n";
    myfile << "         ...'lOXNNWWWXx,.                                                                                                .',:xXWMMMMMMMMMMWXkoll;.\n";
    myfile << "        ..'',lOXNNNWWXd,.                                                                                                ...'oKWMMMMMMMMMMWXOddo:.\n";
    myfile << "        .',;;oOXNNXXX0o,                ......                                             ......                          ..lKWMMMMMMMMMMWXOxddc.\n";
    myfile << "        .,;;:oONWNXKKOo'         .;cclllllllllllccc:'                               .':cccllllllllllccc;.                   .lKWMMMMMMMMMMWX0kxxc.\n";
    myfile << "        .;cccd0NWN0kxdc'        .cOXXK0000000000KXXKo.                              .oKXXK0000000000KXXOc.                  .lKWWMMMMMMMMWWN0kxxc.\n";
    myfile << "        .:llld0NWXOxol:.        .lKNOl;,,,,,,,,;ckXXd'.                             'dXXkc;;,,,,,,;;lON0l.                  .c0WMMMMMMMMMMWN0kkxc.\n";
    myfile << "        .:oooxKNWXOdlc;.       ..oKXx,.        .'oKXd'.                            .,xXKo'.        .,xXKl.                  .c0WMMMMMMMMMMWN0Okkl.\n";
    myfile << "        .cdxxkKWWXkl:;,.       .'oKXx'          .oKXd,.                            .,xXKo.          'xXKo'.                 .c0WMMMMMMMMMMWNKOkkl.\n";
    myfile << "        .:dxxkKWWXkl:,'.       .'oKXx'          .oKXd,.                            .,xXKo.          'xXKo'.                 .c0WMMMMMMMMMMWNKOkkl.\n";
    myfile << "        .cxkkOKWWXkc,'..       ..oKXx,.        .'oKXd,.                            .,dXKo'.        .,xXKl.                 ..c0WMMMMMMMMMMWNKkkxl.\n";
    myfile << "        .cxkkOXWWXkc,'..        .lKXOl;,,,,,',,;ckXXd'                             .'dXXkc;,,,,',,,;lONKl.                ...c0NMMMMMMMMMMWN0kxxl.\n";
    myfile << "        .cxkkOKNWXkc,'..        .cOXXK000000000KKXNKo.                              .oKNXK0000000000KXXOc.                ...cONWMMMMMMMMMWN0kxxc.\n";
    myfile << "        .cxOOOKNWXkc,'..         .:llooooooooooooolc'.                              .'cloooooooooooooll:.                ...'cONWMMMMMMMMWWN0xdo:.\n";
    myfile << "        .:xkOOKNNXkc,''.             ............                                        .............                   ..',lONWMMMMMMMMMWN0xol:.\n";
    myfile << "        .:xOOO0XXKkl;,,.                                                                                                 .',;lONWMMMMMMMMMWN0dll;.\n";
    myfile << "        .;xOOO0KKKkocc:,.                                .;ccloxkkkkkOOOOOO00OO00kl'                                     .:loxKNWMMMMMMMMMWNOl;,.\n";
    myfile << "        .;dOOOO0K0Oxool;.                                ':oddxO0000000000000000Okl.                                     'lxkOXWWWMMMMMMMMWNkc'..\n";
    myfile << "        .;dOOOO000Okxxdc.                                .',;;:ccccccccccccccc::::'.                                    .;kKXXNWMMMMMMMWWMWNk;..\n";
    myfile << "        .;dOOOOOOO00KK0d'                                 ....',,,,,,,,,,,,,,,,,,'.                                     .:OXNNWWMMMMMMMWWWWXx;.\n";
    myfile << "        .;dkOOOOOO0KXNXk:...                               ........................                                  ...'oKWWWWMMMMMMMWWNXXKd,.\n";
    myfile << "         ,oxxxkOOO0KXNNKOxxdo:;;;,......                                                                             .',:dKWWMMMMMMMMMWWXKK0d'\n";
    myfile << "         'ldddxkOO0XNNNNWWWNKxdddl;,,,......                                                     ..........'',,,;;;;:lodx0NWWMMMMMMMMMWX0kxdc.\n";
    myfile << "         'cllodkOO0KKXXXNWWWNK000Okxxxdoooooooooooooolcc::;;;;;,,,,,'''''..''''.......''''''',,,;:ccccodxxk0KKKKKXXXXNNNWWWMMMMMMMMMMMWXklcc;.\n";
    myfile << "         .;::coxOOO0000KNWMWWWWWWWWWWWWWWWWWWWWWNNNNXKOkkxdoooolcccc:::::;;;;;;;;;;;;;;;;::::ccclodxxxkO0KKNWWWWWWMMMMMMMMMMMMMMMMMMMMWKd:;;'.\n";
    myfile << "         .,;;;lxkOOO0O00XWWMMMMMMMMMMMMMMMMMMMMWWWWWNXKKK00000OOOOOkkkkkkkkkkkkkkkkkkOOOOOO000000KXXXXXNNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMW0l....\n";
    myfile << "          ....:dkOOOOOO0XNWWWMMMMMMMMMMMMMMMMMMMMWMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWN0c.\n";
    myfile << "          .. .;dkOOOOOO0KNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXKO:.\n";
    myfile << "             .,oxkkOOOOO0KKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKK0k:.\n";
    myfile << "              'lxkkkOOOOOO00KNWMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKxdol,\n";
    myfile << "              .:oddxkOOOOOOOKNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXk:''..\n";
    myfile << "              .';:coxOOOOOOO0KXXXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXx,....\n";
    myfile << "              ..',;lxOOOOOOO0KKKKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK00kl.\n";
    myfile << "               ....:dkOOOOOOO0000KXNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kxxc.\n";
    myfile << "                  .,okOOOOOOOOOOO0KXXNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWKdc::,.\n";
    myfile << "                   ':oodxkOOOOOOOO0KKKXNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMWWWWNO:. .\n";
    myfile << "                   .',;:oxOOOOOOOOOOO0KXNNNWWMWMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXKx;.\n";
    myfile << "                    .'',cdkOOOOOOOOOOO0KXXXNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkoll;.\n";
    myfile << "                      ..,lxxkkOOOOOOOOO00O0KXNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWWWN0o:,,'.\n";
    myfile << "                        'cddxkOOOOOOOOOOOOO0KXXXNWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0Oko;'...\n";
    myfile << "                        .,;:cdkOOOOOOOOOOOOO0000KKXXXNNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo::,.\n";
    myfile << "                         ...'cxOOOOOOOOOOOOOOOOOOO000XNNNWWWWWMMMMMWWWWMMMMMMMMMMMMMMMMMMWMMMMWMMMWWWWWWWWWWWWWWWWWWXkl:;,.\n";
    myfile << "                        ...';lxOOOOOOOOOOOOOOOOOOO000KKKKXXXXXXNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNXXXXXKKKKKK00Oxolc;.\n";
    myfile << "                       .'codxkkOOOOOOOOOOOOOOOOOOOOOOOOOOO00OO0000KKKXXXXXXXNNNNNNNNWWWWWWWWWNNNNNNXXXKKKK00OOOOOOOOkxdolc'.\n";
    myfile << "                     ...,okOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000KKKKKKKXXXXXXXXXXXXXXXXXXKKKKKKKK000000OOOOOO0OO0000Odlll:'\n";
    myfile << "                    .,::lk0KK000OOOkxxkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000O000OOOO000OOOOOOOOOOOOOOOOOOOOOOOO000XNWWNXKKKk:.\n";
    myfile << "                   .,oxkOKNNNXK000OkddxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkk0XWWWNXXXOl'...\n";
    myfile << "                   .;dkkOKNNXOxdoolc::cdkOOOOkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkxxxxkkOOOO00OOkxddddoook0XNNWWWWXxc;;'.\n";
    myfile << "                ...'cxkOOKXN0o,....   .cxOOOkxddddddxxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkxxdddxkOOO0000OxdddoolcldOKKXNWWWXOocc;.\n";
    myfile << "                ...'cxkO0KXX0l.       .cxOOOkxxxdddoodddddxxxkxkkkkkkkOOOOOOOOOkxxxddooodddxxkOOO00KXXXXNNX0xollc;'..;ldxk0XWWNKOOkd;.\n";
    myfile << "                ...,cxkOO0KKOl'    ...,lkOOOOOkkkdl:::;;,,;clloodxxxkkkOOOOOOOkdolcc:;,,;:ccokKNNNNWWWWMMWWKxc;;,.   .,clokKWWWNXXXk:.\n";
    myfile << "               ..'',cxkOO000ko'    ..':okOOOOOOOkdl:;;,''',:ccllooodddxxxxxxxxdocc:c::::clooxOXWWWWWMMMMMMWXkl::;.   .,::lxKNWWNXNXOc.\n";
    myfile << "                ...':dkOO0KXKx;.  ..',:oxkOOOOOOOkxdoddddddlc:;;,..............',,;:ok0KKXXXNNWWWWWMMMMMMMWXOocc:'.  ..,;:oONWWWWWW0l.\n";
    myfile << "                ...':dkOO0KXKx;.  ..',:oxkOOOOOOOkxdoddddddlc:;;,..............',,;:ok0KKXXXNNWWWWWMMMMMMMWXOocc:'.  ..,;:oONWWWWWW0l.\n";
    myfile << "                   .;okkOKNWNOl'..',,;:oxkOOOOOOOOOOO0KXXXKOdolc,'...     ....';lddk0NWWWWWMMMMMMMMMMMMMMWWXko:::'   .;loox0NWWNXKKOl.\n";
    myfile << "                    .coddk0KK0Oxxxdl:;:oxkOOOOOOOOOO0KNWWWWWNNX0xool:.   .,::clxKNWWWWWMMMMMMMMMMMMMMMMMMMWXkl;;;..  .cdxxkKNWWNK00kl.\n";
    myfile << "                    .;lloxO000KKK0Odc:cokkOOOOOOOOOO0KNWMMMMMWWXOxxxo;...,cooddOXWMMMMMMMMMMMMMMMMMMMMMMMMWN0xlll:,',cxO0KKNWWNKkdol;.\n";
    myfile << "                     .'';lxkkO0KXXK0OkOOOOOOOOOOOOOO0KNWMMMMMMWWNXXXK0kkO0KXXXXNWWMMMMMMMMMMMMMMMMMMMMMMMMWWX0kxxxxdxOXNWWWWWWN0o:;;'.\n";
    myfile << "                        .,oxdxOXWWWWWWWX0OOOOOOOOOOO0KNWWMMMMMMMMWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0kxkkOOOKNWMMWNNXKkc'...\n";
    myfile << "                         ,ldookKNWWWWWWN0OOOOOOOOOOOO0XWWWWWMMMMMMMMWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMWNKOkO0XXNNWWMWNKkdoc'\n";
    myfile << "                         'clllxKNNWWWWWNKOOOOOOOOOOOO0KNWWWWMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWNKOkOKNWWWWNNNXOdlc;.\n";
    myfile << "                         .:cccd0XXNNNNNX0OOkOOOOOOOOO0KXNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXK0KK000KXNWWXkoccc;'...\n";
    myfile << "                         ..''':xOOOO00OkxdddxkOOOOOOOO0KXKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWXOxxkO0KXXNWWN0l.\n";
    myfile << "                             .,lxxxxkxxxdooodxkOOOOOOO00K0KXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xlcldOXXXXXX0x:.\n";
    myfile << "                              .,:::c:::clooloxkOOOOOOOO0000XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXx:...;dXWN0kdoc'.\n";
    myfile << "                                       .;loooxkOOOOOOOOOOOOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWXx,   .l0XKOdl:;.\n";
    myfile << "                                       .,cllldkOOOOOOOOOOOOKNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNKd,    .;::,'....\n";
    myfile << "                                        .,,,;lxOOOOOOOOOOOO0KXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXX0d,\n";
    myfile << "                                        ..'.'cdkOOOOOOOOOOO0KKKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOxdc.\n";
    myfile << "                                         ....,lodxkOOOOOOOOO000KXNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd;...\n";
    myfile << "                                             .;cloxkOOOOOOOOOOO0KNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo'\n";
    myfile << "                                             .;lodxOOOOOkkkkOOOO0KXXXNWWWWWWMMMMMMMMMMMMMMMMMMMMMWKd,..\n";
    myfile << "                                             .:oxxkO00OkxdxkkOOOOOOO0KNNNWWWWMMMMMWWWMMMMMMMMMMMMWKd,...\n";
    myfile << "                                             .:dxkO000OkxddxxxxxxkxxkO0KKKKXXXXXKK00KXNWWWWMMMMMMWXd,...\n";
    myfile << "                                             .cdkOKXNX0xolc:,'.',;:::cllllllllll:,'':xKXNNWWMMMMMWXd,...\n";
    myfile << "                                             .cxO0XWWNKdc;;'.   ..'',,;:::;;;;;,'...'o0XXNWWMMMMMWXd,..\n";
    myfile << "                                             .cxO0XWWWN0kxxoc;;;,''''.....',,,,;:ccldOXNWWWMMMWWMWKd'\n";
    myfile << "                                             .cxO0XWWMWWWWNXKOOxl,....    ..''',cxkO0XWWWMMMMMWWWWKo'\n";
    myfile << "                                             .:xO0XNWWWWWMWWXK0Od:'...    ';;::cdO0KKNWWMMMMMWWNXXOl.\n";
    myfile << "                                             .;okOKXNNWWWMMWWNNXOo:;;'.  .:odxxkKNNWWWWMMMMMMWNK0Ox:.\n";
    myfile << "                                             .;oxk0KXXNWWMMMMMWN0dc::,.. .cdxOO0XWMMMMWMWWNNNXKOxdl;.\n";
    myfile << "                                             ..;:coxkkOKNWMMMMWN0dc::,.. .cdxOO0XWMMMWWMWXOxxxo:,...\n";
    myfile << "                                                 .':cclkXWMMMMWWKxlc:,.. .:oxOO0XNWMMWWWWKxlll:'.\n";
    myfile << "                                               ...;cllokKNNNNNNXOo:;,'.. .:odOO0KNWWWWWWWX0kkkd:'..\n";
    myfile << "                                             .,lddxxkkkO00KKKKK0xc,....  .;ldkOOKNWWWWWWWWNNNNKd:'..\n";
    myfile << "                                             .:dkkkkxkkkOOOOOOOkd:'...    ,cldxxk0KKKKK000OOOOxl;...\n";
    myfile << "                                              .',,,,,,,,,,,,,,,,'..       ...'''''',,''''.......\n";
    myfile << "\n";

    myfile.close();
    return 0;
}
int printLemonBot() {
    cout << "                                                                .....',,;;;;;;;;,,,;;;::::;;;;,'....\n";
    cout << "                                                             ...,ldxxO0KKKKKKKKKKKKKKKXXXK0OOOxoc;,.\n";
    cout << "                                                            ...':okOO0KXXXKKKKKK000000000Okkxxdoc::,'''..\n";
    cout << "                                                           .;odxdolllcc:::;;;;;;;,,,,'''.''''',:clodxO0kc.\n";
    cout << "                                                           .l0NN0o:;,'...............      ....;codk0XNKd,.\n";
    cout << "                                                         ..'lOXX0xollc:;;;;;;;;;;;::::;;;;::ccccccldxOOkdc;;,.\n";
    cout << "                                                       .',;:okOOOkkkkkkkkxkkkkkkkkkkkkkkkkkxkkxoc::lodxddoool,.\n";
    cout << "                                                      ..,::coxOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkxolldxkkkkxxdo;.\n";
    cout << "                                              ..'';:cllodxxxkOO00OOOOOOOOOOOOOOOOOOOO000000000000000KXXK0OOkxc.\n";
    cout << "                                             ..,:coxOOO0000000000000000OOOOOOOOOO000000KKKKKKKKKXXXXXNNXK000ko,....\n";
    cout << "                                         ..',;coddk0KXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNNNNNNNNNNNWWWWWWWWWWWWNNNNKOkkdc'.\n";
    cout << "                                        .;dO00KXNNNWWWWWWWWWWWWWWWWMMMMWMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMWWWNNN0d;....\n";
    cout << "                                     ....ckXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNX0xdoo:'.\n";
    cout << "                                   .;oxxxOXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNXOc.\n";
    cout << "                                 ..'lKWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWKd:,,.\n";
    cout << "                               .';:lxXWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMWWXK0Ol.\n";
    cout << "                              .;xKXXNWMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWXx,.\n";
    cout << "                           ...'cONWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWN0dllc,.\n";
    cout << "                          .,ldxOXWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK0Okc.\n";
    cout << "                          .:OXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMWNXKK0o;...\n";
    cout << "                      ....,o0NNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMWWWWWXkl;,'.\n";
    cout << "                     .,loodOXWWWWWMMMMWWWWMMWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNWWWWWWMMMMMMMMMMMMWN0dlc;.\n";
    cout << "                     .:dkxk0NWMWWNNNXKK0000000OOOkO0KXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdollcccccoooodxkkOKNWWWWWMMMMMMMMMMMWNK0Oxc.\n";
    cout << "                   ..'l0XXXNWWWNKOOkdc,,,,''.......;oxxx0NWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo'...    ..''';clox0XWWWWWMMMMMMMMMMMWWNNN0o'\n";
    cout << "                  ...,dKWWWWWWNXOdddl'.....        'lddxONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd;''........''',;;:ldxxkKNWWWWWMMMMMMWWWWNKd,...\n";
    cout << "                 .,:coOXWWWXOkxo:,,,'...........  .;dkxk0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkocc:,''.......     ...,oKWWWWWWMMMMMMMMWWXk:'...\n";
    cout << "                 ,oO0KXWWWNOl;'..           .......:dkkOKNWWMMMWWWWWWWMMMWWWWMMWWWMMMMMMMWNOdoll:;;;,''''....... .'l0NNNWWMMMMMMMWMMWNOl:;;'.\n";
    cout << "                .,dKXXNWMWNOo:;,'....'',,,;;;::cc:cdO00KXWWMWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMWXK0000OOOOOOOOOkkkxl;'';oOKKKXWWMWMMMMMMMWWKkxdd:.\n";
    cout << "             ....:kXWWWWMWWKkxdddxxxkO0KKKKKKXXXXXXNNWWWWWWMMWWWWWWNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKxc,,:ok000XWWMMMMMMMMMMWX0OOxc.\n";
    cout << "             .'',cONWMMMMWWX0kkkOOOO0XNNNNNXXXXKKKKKKKK000000OOOOOOkkxxxxxxxxxxxxxxxxxxxxddxdxxxxkkkkO0OO0XNNX0kxxk0XNXXNWMMMMMMMMMMMWNXXXKd.\n";
    cout << "             ';::o0NWMMMMWWN0Okkddooooooollc::;;,,,,,,''''''.....................................''',:lccoOXNWNNNNWWWWWWWMMMMMMMMMMMMMWWWWNx,\n";
    cout << "            .,cookKNWMMMMWWN0Okxl:::;,'''.....                                                  .....,;,,:dkOOO0000KNWWWWMMMMMMMMMMMMMWWWWNk,\n";
    cout << "            .,oxxOXWWWNK00Oxoc::,'''.......                                                              ......,,,;lkKKKNWMMMMMMMMMMMMMMMWNO:....\n";
    cout << "            .:x00KNWWN0o:;,'.                                                                                  ....,okkk0XNNWWWWMMMMMMMMMMWOc'...\n";
    cout << "            .:kKXNWWWNkc'...                                                                                       ..'',:oxxkKNWMMMMMMMMMMW0o;;;'.\n";
    cout << "          ...ckKXNWWWXx;..                                                                                              .';:lkNWMMMMMMMMMMWKxc::,.\n";
    cout << "         ...'lOXNNWWWXx,.                                                                                                .',:xXWMMMMMMMMMMWXkoll;.\n";
    cout << "        ..'',lOXNNNWWXd,.                                                                                                ...'oKWMMMMMMMMMMWXOddo:.\n";
    cout << "        .',;;oOXNNXXX0o,                ......                                             ......                          ..lKWMMMMMMMMMMWXOxddc.\n";
    cout << "        .,;;:oONWNXKKOo'         .;cclllllllllllccc:'                               .':cccllllllllllccc;.                   .lKWMMMMMMMMMMWX0kxxc.\n";
    cout << "        .;cccd0NWN0kxdc'        .cOXXK0000000000KXXKo.                              .oKXXK0000000000KXXOc.                  .lKWWMMMMMMMMWWN0kxxc.\n";
    cout << "        .:llld0NWXOxol:.        .lKNOl;,,,,,,,,;ckXXd'.                             'dXXkc;;,,,,,,;;lON0l.                  .c0WMMMMMMMMMMWN0kkxc.\n";
    cout << "        .:oooxKNWXOdlc;.       ..oKXx,.        .'oKXd'.                            .,xXKo'.        .,xXKl.                  .c0WMMMMMMMMMMWN0Okkl.\n";
    cout << "        .cdxxkKWWXkl:;,.       .'oKXx'          .oKXd,.                            .,xXKo.          'xXKo'.                 .c0WMMMMMMMMMMWNKOkkl.\n";
    cout << "        .:dxxkKWWXkl:,'.       .'oKXx'          .oKXd,.                            .,xXKo.          'xXKo'.                 .c0WMMMMMMMMMMWNKOkkl.\n";
    cout << "        .cxkkOKWWXkc,'..       ..oKXx,.        .'oKXd,.                            .,dXKo'.        .,xXKl.                 ..c0WMMMMMMMMMMWNKkkxl.\n";
    cout << "        .cxkkOXWWXkc,'..        .lKXOl;,,,,,',,;ckXXd'                             .'dXXkc;,,,,',,,;lONKl.                ...c0NMMMMMMMMMMWN0kxxl.\n";
    cout << "        .cxkkOKNWXkc,'..        .cOXXK000000000KKXNKo.                              .oKNXK0000000000KXXOc.                ...cONWMMMMMMMMMWN0kxxc.\n";
    cout << "        .cxOOOKNWXkc,'..         .:llooooooooooooolc'.                              .'cloooooooooooooll:.                ...'cONWMMMMMMMMWWN0xdo:.\n";
    cout << "        .:xkOOKNNXkc,''.             ............                                        .............                   ..',lONWMMMMMMMMMWN0xol:.\n";
    cout << "        .:xOOO0XXKkl;,,.                                                                                                 .',;lONWMMMMMMMMMWN0dll;.\n";
    cout << "        .;xOOO0KKKkocc:,.                                .;ccloxkkkkkOOOOOO00OO00kl'                                     .:loxKNWMMMMMMMMMWNOl;,.\n";
    cout << "        .;dOOOO0K0Oxool;.                                ':oddxO0000000000000000Okl.                                     'lxkOXWWWMMMMMMMMWNkc'..\n";
    cout << "        .;dOOOO000Okxxdc.                                .',;;:ccccccccccccccc::::'.                                    .;kKXXNWMMMMMMMWWMWNk;..\n";
    cout << "        .;dOOOOOOO00KK0d'                                 ....',,,,,,,,,,,,,,,,,,'.                                     .:OXNNWWMMMMMMMWWWWXx;.\n";
    cout << "        .;dkOOOOOO0KXNXk:...                               ........................                                  ...'oKWWWWMMMMMMMWWNXXKd,.\n";
    cout << "         ,oxxxkOOO0KXNNKOxxdo:;;;,......                                                                             .',:dKWWMMMMMMMMMWWXKK0d'\n";
    cout << "         'ldddxkOO0XNNNNWWWNKxdddl;,,,......                                                     ..........'',,,;;;;:lodx0NWWMMMMMMMMMWX0kxdc.\n";
    cout << "         'cllodkOO0KKXXXNWWWNK000Okxxxdoooooooooooooolcc::;;;;;,,,,,'''''..''''.......''''''',,,;:ccccodxxk0KKKKKXXXXNNNWWWMMMMMMMMMMMWXklcc;.\n";
    cout << "         .;::coxOOO0000KNWMWWWWWWWWWWWWWWWWWWWWWNNNNXKOkkxdoooolcccc:::::;;;;;;;;;;;;;;;;::::ccclodxxxkO0KKNWWWWWWMMMMMMMMMMMMMMMMMMMMWKd:;;'.\n";
    cout << "         .,;;;lxkOOO0O00XWWMMMMMMMMMMMMMMMMMMMMWWWWWNXKKK00000OOOOOkkkkkkkkkkkkkkkkkkOOOOOO000000KXXXXXNNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMW0l....\n";
    cout << "          ....:dkOOOOOO0XNWWWMMMMMMMMMMMMMMMMMMMMWMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWN0c.\n";
    cout << "          .. .;dkOOOOOO0KNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXKO:.\n";
    cout << "             .,oxkkOOOOO0KKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKK0k:.\n";
    cout << "              'lxkkkOOOOOO00KNWMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKxdol,\n";
    cout << "              .:oddxkOOOOOOOKNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXk:''..\n";
    cout << "              .';:coxOOOOOOO0KXXXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXx,....\n";
    cout << "              ..',;lxOOOOOOO0KKKKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK00kl.\n";
    cout << "               ....:dkOOOOOOO0000KXNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kxxc.\n";
    cout << "                  .,okOOOOOOOOOOO0KXXNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWKdc::,.\n";
    cout << "                   ':oodxkOOOOOOOO0KKKXNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMWWWWNO:. .\n";
    cout << "                   .',;:oxOOOOOOOOOOO0KXNNNWWMWMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXKx;.\n";
    cout << "                    .'',cdkOOOOOOOOOOO0KXXXNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkoll;.\n";
    cout << "                      ..,lxxkkOOOOOOOOO00O0KXNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWWWN0o:,,'.\n";
    cout << "                        'cddxkOOOOOOOOOOOOO0KXXXNWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0Oko;'...\n";
    cout << "                        .,;:cdkOOOOOOOOOOOOO0000KKXXXNNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo::,.\n";
    cout << "                         ...'cxOOOOOOOOOOOOOOOOOOO000XNNNWWWWWMMMMMWWWWMMMMMMMMMMMMMMMMMMWMMMMWMMMWWWWWWWWWWWWWWWWWWXkl:;,.\n";
    cout << "                        ...';lxOOOOOOOOOOOOOOOOOOO000KKKKXXXXXXNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNXXXXXKKKKKK00Oxolc;.\n";
    cout << "                       .'codxkkOOOOOOOOOOOOOOOOOOOOOOOOOOO00OO0000KKKXXXXXXXNNNNNNNNWWWWWWWWWNNNNNNXXXKKKK00OOOOOOOOkxdolc'.\n";
    cout << "                     ...,okOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000KKKKKKKXXXXXXXXXXXXXXXXXXKKKKKKKK000000OOOOOO0OO0000Odlll:'\n";
    cout << "                    .,::lk0KK000OOOkxxkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000O000OOOO000OOOOOOOOOOOOOOOOOOOOOOOO000XNWWNXKKKk:.\n";
    cout << "                   .,oxkOKNNNXK000OkddxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkk0XWWWNXXXOl'...\n";
    cout << "                   .;dkkOKNNXOxdoolc::cdkOOOOkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkxxxxkkOOOO00OOkxddddoook0XNNWWWWXxc;;'.\n";
    cout << "                ...'cxkOOKXN0o,....   .cxOOOkxddddddxxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkxxdddxkOOO0000OxdddoolcldOKKXNWWWXOocc;.\n";
    cout << "                ...'cxkO0KXX0l.       .cxOOOkxxxdddoodddddxxxkxkkkkkkkOOOOOOOOOkxxxddooodddxxkOOO00KXXXXNNX0xollc;'..;ldxk0XWWNKOOkd;.\n";
    cout << "                ...,cxkOO0KKOl'    ...,lkOOOOOkkkdl:::;;,,;clloodxxxkkkOOOOOOOkdolcc:;,,;:ccokKNNNNWWWWMMWWKxc;;,.   .,clokKWWWNXXXk:.\n";
    cout << "               ..'',cxkOO000ko'    ..':okOOOOOOOkdl:;;,''',:ccllooodddxxxxxxxxdocc:c::::clooxOXWWWWWMMMMMMWXkl::;.   .,::lxKNWWNXNXOc.\n";
    cout << "                ...':dkOO0KXKx;.  ..',:oxkOOOOOOOkxdoddddddlc:;;,..............',,;:ok0KKXXXNNWWWWWMMMMMMMWXOocc:'.  ..,;:oONWWWWWW0l.\n";
    cout << "                ...':dkOO0KXKx;.  ..',:oxkOOOOOOOkxdoddddddlc:;;,..............',,;:ok0KKXXXNNWWWWWMMMMMMMWXOocc:'.  ..,;:oONWWWWWW0l.\n";
    cout << "                   .;okkOKNWNOl'..',,;:oxkOOOOOOOOOOO0KXXXKOdolc,'...     ....';lddk0NWWWWWMMMMMMMMMMMMMMWWXko:::'   .;loox0NWWNXKKOl.\n";
    cout << "                    .coddk0KK0Oxxxdl:;:oxkOOOOOOOOOO0KNWWWWWNNX0xool:.   .,::clxKNWWWWWMMMMMMMMMMMMMMMMMMMWXkl;;;..  .cdxxkKNWWNK00kl.\n";
    cout << "                    .;lloxO000KKK0Odc:cokkOOOOOOOOOO0KNWMMMMMWWXOxxxo;...,cooddOXWMMMMMMMMMMMMMMMMMMMMMMMMWN0xlll:,',cxO0KKNWWNKkdol;.\n";
    cout << "                     .'';lxkkO0KXXK0OkOOOOOOOOOOOOOO0KNWMMMMMMWWNXXXK0kkO0KXXXXNWWMMMMMMMMMMMMMMMMMMMMMMMMWWX0kxxxxdxOXNWWWWWWN0o:;;'.\n";
    cout << "                        .,oxdxOXWWWWWWWX0OOOOOOOOOOO0KNWWMMMMMMMMWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0kxkkOOOKNWMMWNNXKkc'...\n";
    cout << "                         ,ldookKNWWWWWWN0OOOOOOOOOOOO0XWWWWWMMMMMMMMWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMWNKOkO0XXNNWWMWNKkdoc'\n";
    cout << "                         'clllxKNNWWWWWNKOOOOOOOOOOOO0KNWWWWMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWNKOkOKNWWWWNNNXOdlc;.\n";
    cout << "                         .:cccd0XXNNNNNX0OOkOOOOOOOOO0KXNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXK0KK000KXNWWXkoccc;'...\n";
    cout << "                         ..''':xOOOO00OkxdddxkOOOOOOOO0KXKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWXOxxkO0KXXNWWN0l.\n";
    cout << "                             .,lxxxxkxxxdooodxkOOOOOOO00K0KXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xlcldOXXXXXX0x:.\n";
    cout << "                              .,:::c:::clooloxkOOOOOOOO0000XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXx:...;dXWN0kdoc'.\n";
    cout << "                                       .;loooxkOOOOOOOOOOOOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWXx,   .l0XKOdl:;.\n";
    cout << "                                       .,cllldkOOOOOOOOOOOOKNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNKd,    .;::,'....\n";
    cout << "                                        .,,,;lxOOOOOOOOOOOO0KXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXX0d,\n";
    cout << "                                        ..'.'cdkOOOOOOOOOOO0KKKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOxdc.\n";
    cout << "                                         ....,lodxkOOOOOOOOO000KXNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd;...\n";
    cout << "                                             .;cloxkOOOOOOOOOOO0KNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo'\n";
    cout << "                                             .;lodxOOOOOkkkkOOOO0KXXXNWWWWWWMMMMMMMMMMMMMMMMMMMMMWKd,..\n";
    cout << "                                             .:oxxkO00OkxdxkkOOOOOOO0KNNNWWWWMMMMMWWWMMMMMMMMMMMMWKd,...\n";
    cout << "                                             .:dxkO000OkxddxxxxxxkxxkO0KKKKXXXXXKK00KXNWWWWMMMMMMWXd,...\n";
    cout << "                                             .cdkOKXNX0xolc:,'.',;:::cllllllllll:,'':xKXNNWWMMMMMWXd,...\n";
    cout << "                                             .cxO0XWWNKdc;;'.   ..'',,;:::;;;;;,'...'o0XXNWWMMMMMWXd,..\n";
    cout << "                                             .cxO0XWWWN0kxxoc;;;,''''.....',,,,;:ccldOXNWWWMMMWWMWKd'\n";
    cout << "                                             .cxO0XWWMWWWWNXKOOxl,....    ..''',cxkO0XWWWMMMMMWWWWKo'\n";
    cout << "                                             .:xO0XNWWWWWMWWXK0Od:'...    ';;::cdO0KKNWWMMMMMWWNXXOl.\n";
    cout << "                                             .;okOKXNNWWWMMWWNNXOo:;;'.  .:odxxkKNNWWWWMMMMMMWNK0Ox:.\n";
    cout << "                                             .;oxk0KXXNWWMMMMMWN0dc::,.. .cdxOO0XWMMMMWMWWNNNXKOxdl;.\n";
    cout << "                                             ..;:coxkkOKNWMMMMWN0dc::,.. .cdxOO0XWMMMWWMWXOxxxo:,...\n";
    cout << "                                                 .':cclkXWMMMMWWKxlc:,.. .:oxOO0XNWMMWWWWKxlll:'.\n";
    cout << "                                               ...;cllokKNNNNNNXOo:;,'.. .:odOO0KNWWWWWWWX0kkkd:'..\n";
    cout << "                                             .,lddxxkkkO00KKKKK0xc,....  .;ldkOOKNWWWWWWWWNNNNKd:'..\n";
    cout << "                                             .:dkkkkxkkkOOOOOOOkd:'...    ,cldxxk0KKKKK000OOOOxl;...\n";
    cout << "                                              .',,,,,,,,,,,,,,,,'..       ...'''''',,''''.......\n";
    cout << "\n";
}
int logo() {
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK0Okxdollcc::::::::cloxOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kdlc;'...                      .,cxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0koc,..         ...',;::cccccccc:,'.      .;dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKko:'.      ..,:loxk0KXNWWMMMMMMMMMMMMWNKOd:.     .c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl,.      .;cdk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkl.    .:x0XNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0d;.     .,lx0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx,      .';ldkKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd;.    .,lkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk,     ......':okKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk:.    .;o0NMMMMMMMMMMMMMMMMMMWWNXXK00OOkkkxxxxxk0KNWMMMMMMMMMMNd.    .,;,'.....;lk0000000000000000NMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMXd,     'o0WMMMMMMMMMMMMMMWWXK0kxdolc::;;;;;;;,,,,,,;:lx0NMMMMMMMMMMK:    .';;;;;,'.............     .xMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMXd'    .:kNMMMMMMMMMMMMMWX0kdoc:;;;;;,,''.................'ckNMMMMMMMMMNd.    .,:cokOO0Okkkkkkkkd.      dMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMNk'    .:OWMMMMMMMMMMMWX0xoc:;,,''.........,;:cloodddooc;.    .;OWMMMMMMMMWO,    .,;:ld0WMMMMMMMMMX;      dMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMK:     ;OWMMMMMMMMMMWXOdc;,'.......    ,okKXWMMMMMMMMMMMMWXk;    .oXMMMMMMMMMK:    .,;;l0WMMMMMMMMMX;      dMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMWk'    .dNMMMMMMMMMMN0dc;'.....;cdkk;  .dNMMMMMMMMMMMMMMMMMMMMNd.    ;0MMMMMMMMMXl    .;xXMMMMMMMMMMMX;      dMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMWx.    ,OWMMMMMMMMMNOo:'.. .;oOXWMMMk. .dWMMMMMMMMMMMWWWWWMMMMMMW0,    'kWMMMMMMMMNo.  'kWMMMMMMMMMMMMX;      dMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMWx.    ;KMMMMMMMMMW0o;'. .:xKWMMMMMMWo  ;KMMMMMMNkl:;;;,,,;xWMMMMMMK:    .xWMMMMMMMMWd.;0MMMMMMMMMNxckWX:.'.   dMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMk.    ,KMMMMMMMMMXx:,. .c0WMMMMMMMMMMo  dWMMMMMWo     ...  .kMMMMMMMX:    .xWMMMMMMMMWKXMMMMMMMMMK:  .oKo,;,.  dMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMX;    .kMMMMMMMMWKo;'. ;0WMMMMMMMMMMMMx.,KMMMMMMWl    .,;,.. cWMMMMMMMK;    .xNMMMMMMMMMMMMMMMMMWO'    .ol;;;,. :XMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMd.    lWMMMMMMMMXo;' .lNMMMMWKOxolc:::. cWMMMMMMWo     .'... ;XMMMMMMMM0'    .xNMMMMMMMMMMMMMMMWx.    .,;;;;;;,. oWMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMX:    .kMMMMMMMMNx;'. lNMMMKo,.    ....  dMMMMMMMM0:'........'lXMMMMMMMMWx.    'kNMMMMMMMMMMMMMNo.    .;;;;;;;;;. '0MMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMM0'    ,KMMMMMMMWKc,. ,KMMMO.    .',;;;' .kMMMMMMMMMWNXXXXXXNNNWMMMMMMMMMMX;    .:xNMMMMMMMMMMMXl     ';;;;;;;;;;,..dMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMO.    ;XMMMMMMMWO:,. :NMMWo     ';;;;;. .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX;    .;:kWMMMMMMMMMWl     ';;;;;;;;;;;,. lWMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMO.    ;XMMMMMMMWOc,. ;XMMMK;     .'',;. .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.    ';l0WMMMMMMMMMWk.    .;;;;;;;;;;;,. lWMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMM0'    '0MMMMMMMMXo;. .OMMMMNx;.      .  .xMMMMMMMMMMMMMMMMMMMMMMMMMMWN0d;    .';l0WMMMMMMMMMMMWO'    .;;;;;;;;;;,. dMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMN:    .dMMMMMMMMWO:,. ;KMMMMMWX0kdolll:. oMMMMMMMMMXOOO0000000OOkdoc;'.   ..',;l0WMMMMMMMMMMMMMM0,    .,;;;;;;;;' 'OMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMx.    ;XMMMMMMMMNk:'. ,0WMMMMMMMMMMMMX; ;XMMMMMMMMO'   .....        ...',,;;;l0WMMMMMMMMMMMMMMMMK:    .,c:;;;;,. lWMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMX:     oWMMMMMMMMNkc,. .lKWMMMMMMMMMMNc .dWMMMMMMMMKo,..             ..';;;;lKWMMMMMMMMMMMMMMMMMMNo.   ;Oo;;;,. ;KMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMO'    .dWMMMMMMMMW0o;'. .cxKWMMMMMMMMo  'OMMMMMMMMMMWX0Okxxxdddxd'    .,;;oKWMMMMMMMMKokWMMMMMMMMWk' ;0Xo,;,.  dMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMWk.    .dWMMMMMMMMMNOl;'.. .,lxOXWMMMO.  ,0MMMMMMMMMMMMMMMMMMMMMN:    .,;dXMMMMMMMMMK; .oNMMMMMMMMMXOXMX:.'.   dMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMWk.    .lXMMMMMMMMMMNOo:,'... ..,coxx,   .dXWMMMMMMMMMMMMMMMMMM0'    .:xNMMMMMMMMM0,    cXWMMMMMMMMMMMX;      dMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMW0,     ,kWMMMMMMMMMMWKxl:;;,'.... .      .;ldk0XNWMMMMMMMMMMWo    .:ONMMMMMMMMWO'    .,lONMMMMMMMMMMX;      dMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMXl.    .:0WMMMMMMMMMMWN0xoc;;;;;,''............',::clllllll:.   .cKWMMMMMMMMWx.    .,;;cOWMMMMMMMMMX;      dMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMWO;     .c0WMMMMMMMMMMMMWXOxoc:;;;;;;;;;;;,,''................;xNMMMMMMMMMXl.    .,:lxOXNWWWWWWWWWK,      dMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMNx,     .;xXMMMMMMMMMMMMMMWNKOxdlc:;;;;;;;;;;;;;;;;;;;;;;:oONMMMMMMMMMWO,     .;;:llllllc;,'''''.       dMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMNk;.     'lONMMMMMMMMMMMMMMMMWWXK0Okxddollcccc::::ccldkKWMMMMMMMMMMXo.    .';;;;;,'.....''''''''''''',kMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOl.      'ckXWMMMMMMMMMMMMMMMMMMMMMMWWNNXXXXXXXXNWWMMMMMMMMMMMNk,     .,;;,'....':d0NNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx:.      .;okKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;      .......,cd0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxc'       .,cdOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd,       ..,:lxOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOd:.        .':ldk0XNWMMMMMMMMMMMMMMMMMMMMMMMN0d:.     .cdk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0dc,.          .',:clodxkO000KKKKKKK0Oxo:'.      'oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxl:,..               .........          .ckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kdlc;,...                    .':oONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX00OxddoollcccccclloxOKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";
    cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";
    cout <<"\n";
}
int notFound() {
    cout << ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cloddddddolc:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;oxxxxxxxxxxxxdl,,,,,,,,,,,,,,,cokKXNWWMMMMWWWNKOxl;,,,,,,,,,,,,,,,,,,,,,,,;oxxxxxxxxxxxxxl,,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:kNWMMMMMMMMMMWWk;,,,,,,,,,,,;lkXWMMMMMMMMMMMMMMMMWN0d:,,,,,,,,,,,,,,,,,,,,:kNWMMMMMMMMMMMWk;,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,l0WMMMMMMMMMMMMMWk;,,,,,,,,,,:kXWMMMMMMMMMMMMMMMMMMMMMW0o;,,,,,,,,,,,,,,,,,l0WMMMMMMMMMMMMMWk;,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;oKWMMMMMMMMMMMMMMWk;,,,,,,,,,l0WMMMMMMMMMWWWWWMMMMMMMMMMWXx;,,,,,,,,,,,,,,;oKWMMMMMMMMMMMMMMWk;,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,;xXWMMMMMWWWMMMMMMMWk;,,,,,,,,lKWMMMMMMMMWKkdooox0NWMMMMMMMMNx;,,,,,,,,,,,,;xXWMMMMMWWMMMMMMMMWk;,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,,,,,,,,:kNMMMMMMNOONMMMMMMMWk;,,,,,,,c0WMMMMMMMMNkc,,,,,,;oKWMMMMMMMMXd,,,,,,,,,,,:kNMMMMMMNOONMMMMMMMWk;,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,,,,,,,c0WMMMMMWNx:dNMMMMMMMWk;,,,,,,;xNMMMMMMMMNx;,,,,,,,,,lKWMMMMMMMW0c,,,,,,,,,c0WMMMMMWXx:dNMMMMMMMWk;,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,,,,,;oKWMMMMMWKd;,dNMMMMMMMWk;,,,,,,c0WMMMMMMMW0c,,,,,,,,,,,dNMMMMMMMMNx;,,,,,,,oKWMMMMMWXd;,dNMMMMMMMWk;,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,,,,;dXWMMMMMW0l,,,dNMMMMMMMWk;,,,,,,oXMMMMMMMMNd,,,,,,,,,,,,c0WMMMMMMMWO:,,,,,;dXWMMMMMW0l,,,dNMMMMMMMWk;,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,,,:kNMMMMMMWOc,,,,dNMMMMMMMWk;,,,,,;xNMMMMMMMMXl,,,,,,,,,,,,:kWMMMMMMMW0c',,,:kNMMMMMMWOc,,,,dNMMMMMMMWk;,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,,cOWMMMMMMNk:,,,,,dNMMMMMMMWk;,,,,,;xWMMMMMMMMKl,,,,,,,,,,,,;kWMMMMMMMWKc',,cOWMMMMMWNk:,,,,,dNMMMMMMMWk;,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,oKWMMMMMMXd;,,,,,,dNMMMMMMMWk;,,,,,,xWMMMMMMMMKl,,,,,,,,,,,,:kWMMMMMMMW0c,,oKWMMMMMWXd;,,,,,,dNMMMMMMMWk;,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,;dXWMMMMMMWKkxxxxxxx0WMMMMMMMWKkxxdc,,dNMMMMMMMMNd,,,,,,,,,,,,c0WMMMMMMMWO:;dXWMMMMMMWKkxxxxxxx0WMMMMMMMWKkxxdc,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNx,,lKWMMMMMMMWOc,,,,,,,,,,,dXMMMMMMMMNx;lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNx,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,,;xNMMMMMMMWNx;,,,,,,,,,lKWMMMMMMMWKl,lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx;,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNx,,,c0WMMMMMMMMNx:,,,,,,;o0WMMMMMMMMNd;,lKWMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMWNx,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,:dxkkkkkkkkkkkkkkkkkKWMMMMMMMWXkxxxc,,,,oKWMMMMMMMMWKxollodONWMMMMMMMMNk:,,:dxkkkkkkkkkkkkkkkkkKWMMMMMMMMXkkkxc,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,dNMMMMMMMWk;,,,,,,,,,oKWMMMMMMMMMWWWWWWMMMMMMMMMWNk:,,,,,,,,,,,,,,,,,,,,,,,dNMMMMMMMWk;,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,dNMMMMMMMWk;,,,,,,,,,,cONWMMMMMMMMMMMMMMMMMMMMMWKd;,,,,,,,,,,,,,,,,,,,,,,,,dNMMMMMMMWk;,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,dNMMMMMMMWk;,,,,,,,,,,,;oOXWMMMMMMMMMMMMMMMMMNKd:,,,,,,,,,,,,,,,,,,,,,,,,,,dNMMMMMMMWk;,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,lkO000OOOOo;,,,,,,,,,,,,,;cdOKNWWWMMMMMWWNX0ko:,,,,,,,,,,,,,,,,,,,,,,,,,,,,lkOO000OOOo;,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:codxxxxxxdol:;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout << ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n";
    cout <<"\n";
}

int main() {
    cout << "BOOTING PROTOTYPE LeMOnBoT... \n\nHello World!\n\n...\n\n";
    int num;
    for(int i = 0; i < 10; i++) {
        cout << "Please ask LeMOnBoT one of the following questions: \n\n";
        cout << "1. What is the best company in the world?\n";
        cout << "2. What is the meaning of life?\n";
        cout << "3. SHOW ME LeMOnBoT!\n";
        cout << "4. Who should win the merch this week?\n";
        cout << "5. Can I keep him\n";
        cout << "6. Say Goodbye to LemonBot!\n\n";

        cin >> num;
        cout <<"\n";

        if(num == 1) {
            logo();
        } else if(num == 2) {
            cout << "42\n\n";
        } else if(num == 3) {
            printLemonBot();
        } else if(num == 4) {
            cout << "Definitely Halle, LeMOnBoT heard she put a bit of effort into this program...\n\n";
        } else if(num == 5) {
            cout << "Popping it in the drive for you!\n";
            cout << "...text file downloading... \n\n";
            writeFile();
        } else if(num == 6) {
            cout << "LeMOnBoT will miss you <3\n";
            exit(0);
        } else {
            notFound();
        }

    }
}
